# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OmusubiKororin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OmusubiKororin
  pod 'SSSwiftUIGIFView'

  target 'OmusubiKororinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OmusubiKororinUITests' do
    # Pods for testing
  end

end
